### ISSUE TITLE
Aiuto con openblocks

### ISSUE THREAD

**Issue by billyrudi** [frigi83/traefik-examples#30]
Ciao mi aiuteresti con questa configurazione?
il container è openblocks:
    image: "openblocksdev/openblocks-ce"
    container_name: openblocks         
Grazie Paolo
`

  # Start Traefik with the latest version
  traefik:
    image: traefik:v2.8
    container_name: traefik
    command:
      # Enable Hub communication (open the port 9900 and 9901 by default)
      - --experimental.hub=true
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --providers.docker

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    labels:
      traefik.http.routers.dash.rule: Host(`dash.localhost`)
      traefik.http.routers.dash.service: api@internal

    ports:
      - "80:80"
      - 3000:3000

  openblocks:
    image: "openblocksdev/openblocks-ce"
    container_name: openblocks                    
    #ports:
    #    - "3000:3000"    
    labels:
      - traefik.enable=true
      - "traefik.http.routers. openblocks.rule=Host('localhost')"
      - "traefik.tcp.routers.openblocks.entrypoints=tcpep"
      - "traefik.tcp.routers.openblocks.service=openblocksService"
      - "traefik.tcp.services.openblocksService.loadBalancer.server.port=3000"
    restart: unless-stopped
`

**Comment by frigi83** [comment]
Ciao @billyrudi , mi sembra un po' eccessivo usare trefik per accedere a un sito "solo" con HTTP. Il grande vantaggio di traefik è proprio la gestione automatica dei certificati SSL e rendere sicuro l'accesso al servizio.

Comunque non è possibile usare come nome di dominio `localhost`. Se vuoi puoi guardare questa [guida](https://frigi.ch/2022/06/dominio-gratuito-per-i-progetti-casalinghi/) per usare dei domini gratis.
